#!/usr/bin/env python3
"""Flywheel 零 LLM 聚类 — 失败痕迹 → pattern 簇 → REVIEW_QUEUE.md

用法:
  python flywheel/cluster.py            # 扫描 failures/ → 聚类 → candidates/ + REVIEW_QUEUE.md
  python flywheel/cluster.py --review   # 只刷新 REVIEW_QUEUE.md 状态 (不重聚类)
  python flywheel/cluster.py --example  # 生成 3 条样例失败用于冒烟测试

参考: agentic-stack (Jaccard 0.3 + 稳定 pattern_id) + Google (10+ 阈值) + harpreet (2+ 次才算 pattern)
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

FLYWHEEL = Path(__file__).resolve().parent
FAILURES = FLYWHEEL / "failures"
CANDIDATES = FLYWHEEL / "candidates"
REVIEW_QUEUE = FLYWHEEL / "REVIEW_QUEUE.md"

CLUSTER_SIMILARITY = 0.3     # Jaccard 阈值 (agentic-stack)
MIN_PATTERN_COUNT = 2        # 2+ 次才算 pattern (harpreet)
STALE_DAYS = 7               # 积压门禁: 最老 >7 天
QUEUE_OVERFLOW = 10          # 积压门禁: 队列 >10

STOPWORDS = {"的", "了", "是", "在", "与", "和", "或", "及", "一个", "我们", "你们", "他们", "这个", "那个", "没有", "不能", "失败", "错误", "问题", "出现", "报错"}
WORD_RE = re.compile(r"[a-zA-Z0-9_\u4e00-\u9fff]+")


def norm_text(text: str) -> str:
    """规范化: 去标点/小写/去停用词"""
    words = [w.lower() for w in WORD_RE.findall(text or "")]
    return " ".join(w for w in words if w not in STOPWORDS and len(w) > 1)


def word_set(text: str) -> set[str]:
    return set(norm_text(text).split())


def jaccard(a: set[str], b: set[str]) -> float:
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def pattern_id(seed: str) -> str:
    return hashlib.sha256(seed.encode()).hexdigest()[:12]


def load_failures() -> list[dict]:
    if not FAILURES.exists():
        return []
    out = []
    for f in sorted(FAILURES.glob("*.json")):
        try:
            out.append(json.loads(f.read_text()))
        except (json.JSONDecodeError, OSError) as e:
            print(f"  ! 跳过损坏文件 {f.name}: {e}", file=sys.stderr)
    return out


def cluster(failures: list[dict]) -> list[list[dict]]:
    """Jaccard 贪心聚类 → 簇列表 (≥2 条才保留为 pattern)"""
    records = [(f, word_set(f.get("message", "") + " " + f.get("command", ""))) for f in failures]
    clusters: list[list[dict]] = []
    for rec, ws in records:
        placed = False
        for cl in clusters:
            rep = word_set(cl[0].get("message", "") + " " + cl[0].get("command", ""))
            if jaccard(ws, rep) >= CLUSTER_SIMILARITY:
                cl.append(rec)
                placed = True
                break
        if not placed:
            clusters.append([rec])
    return [c for c in clusters if len(c) >= MIN_PATTERN_COUNT]


def build_patterns(clusters: list[list[dict]]) -> list[dict]:
    patterns = []
    for cl in sorted(clusters, key=len, reverse=True):
        msgs = [f.get("message", "") for f in cl]
        seed = norm_text(msgs[0]) or cl[0].get("id", "unknown")
        pid = pattern_id(seed)
        modes = Counter()
        hosts = Counter()
        stages = Counter()
        first = min(f.get("created_at", "9999") for f in cl)
        for f in cl:
            for m in f.get("failure_modes", []):
                modes[m] += 1
            hosts[f.get("host", "?")] += 1
            stages[f.get("caught_stage", "?")] += 1
        patterns.append({
            "pattern_id": pid,
            "count": len(cl),
            "first_seen": first,
            "failure_modes": dict(modes.most_common(3)),
            "hosts": dict(hosts),
            "caught_stages": dict(stages),
            "representative": msgs[0][:200],
            "failure_ids": [f.get("id", "?") for f in cl],
        })
    return patterns


def render_queue(patterns: list[dict], now: str) -> str:
    lines = [
        "# Flywheel Review Queue",
        f"<!-- auto-generated by cluster.py {now} -- DO NOT EDIT -->",
        "",
        f"## 状态: {len(patterns)} 个 pattern 待审 (积压门禁: 队列>{QUEUE_OVERFLOW} 或 最老>{STALE_DAYS}天)",
        "",
    ]
    for i, p in enumerate(patterns, 1):
        lines += [
            f"### {i}. [{p['pattern_id']}] {p['count']} 条失败 — 首次 {p['first_seen'][:10]}",
            f"- 模式: {', '.join(f'{k}({v})' for k, v in p['failure_modes'].items())}",
            f"- 分布: hosts={p['hosts']} stages={p['caught_stages']}",
            f"- 代表: {p['representative']}",
            f"- 失败: {', '.join(p['failure_ids'][:5])}",
            "- 状态: ⏳ pending (审批需带 rationale; 通过→晋升技能/规则, 拒绝→标注原因)",
            "",
        ]
    if not patterns:
        lines.append("无新 pattern。失败痕迹不足 2 次或聚类未达阈值。")
    return "\n".join(lines)


def write_candidates(patterns: list[dict]) -> None:
    CANDIDATES.mkdir(exist_ok=True)
    for p in patterns:
        (CANDIDATES / f"{p['pattern_id']}.json").write_text(
            json.dumps(p, ensure_ascii=False, indent=2), encoding="utf-8"
        )


def gen_examples() -> None:
    """冒烟测试: 3 条样例失败 (2 条同类 + 1 条独立)"""
    FAILURES.mkdir(exist_ok=True)
    base = [
        {
            "id": "m2max-20260828-001", "created_at": "2026-08-28T10:00:00+08:00",
            "host": "m2max", "project": "pulse-data-engine", "domain": "internal-ops",
            "workflow": "ingest_produce", "harness": "hermes", "skill": "rag-material-factory",
            "instruction": "吞噬视频素材", "input_hash": "a" * 16,
            "context_tokens_before": 1200, "context_tokens_after": 1500,
            "failure_modes": ["missing-error-handling"], "target_use": "skill-gen",
            "raw_input_stored": False, "caught_stage": "pr",
            "message": "yt-dlp 下载失败: Requested format is not available, 视频只有 m3u8 流",
            "command": "yt-dlp -f bestaudio <url>", "redaction_status": "passed",
        },
        {
            "id": "m2max-20260828-002", "created_at": "2026-08-28T11:30:00+08:00",
            "host": "m2max", "project": "pulse-data-engine", "domain": "internal-ops",
            "workflow": "ingest_produce", "harness": "hermes", "skill": "rag-material-factory",
            "instruction": "吞噬视频素材", "input_hash": "b" * 16,
            "context_tokens_before": 1300, "context_tokens_after": 1600,
            "failure_modes": ["missing-error-handling"], "target_use": "skill-gen",
            "raw_input_stored": False, "caught_stage": "manual",
            "message": "yt-dlp 报错: Requested format is not available, 需要 m3u8 直抓",
            "command": "yt-dlp -f bestaudio <url>", "redaction_status": "passed",
        },
        {
            "id": "m2max-20260828-003", "created_at": "2026-08-28T12:00:00+08:00",
            "host": "m2max", "project": "pulse-data-engine", "domain": "compliance",
            "workflow": "kb_gap", "harness": "hermes", "skill": "lightweight-rag",
            "instruction": "知识库缺口复评", "input_hash": "c" * 16,
            "context_tokens_before": 800, "context_tokens_after": 900,
            "failure_modes": ["scope-creep"], "target_use": "rule-fix",
            "raw_input_stored": False, "caught_stage": "review",
            "message": "kb_gap 候选全是 2-3 字碎片词, 无选题价值",
            "command": "python -m scripts.kb_gap --json", "redaction_status": "passed",
        },
    ]
    for rec in base:
        (FAILURES / f"{rec['id']}.json").write_text(
            json.dumps(rec, ensure_ascii=False, indent=2), encoding="utf-8"
        )
    print(f"已生成 {len(base)} 条样例 → flywheel/failures/")


def main() -> int:
    ap = argparse.ArgumentParser(description="Flywheel 零 LLM 聚类")
    ap.add_argument("--review", action="store_true", help="只刷新 REVIEW_QUEUE (不重聚类)")
    ap.add_argument("--example", action="store_true", help="生成样例失败后退出")
    args = ap.parse_args()

    now = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")

    if args.example:
        gen_examples()
        return 0

    failures = load_failures()
    print(f"扫描失败痕迹: {len(failures)} 条")

    if args.review:
        patterns = [json.loads(f.read_text()) for f in sorted(CANDIDATES.glob("*.json"))] if CANDIDATES.exists() else []
    else:
        clusters = cluster(failures)
        patterns = build_patterns(clusters)
        write_candidates(patterns)
        print(f"聚类结果: {len(clusters)} 簇 → {len(patterns)} 个 pattern (≥{MIN_PATTERN_COUNT} 条)")

    REVIEW_QUEUE.write_text(render_queue(patterns, now), encoding="utf-8")
    print(f"REVIEW_QUEUE.md 已更新: {len(patterns)} 个待审 pattern")
    return 0


if __name__ == "__main__":
    sys.exit(main())
